#!/usr/bin/env bash

percent=$1
backlight=/sys/class/backlight/intel_backlight
numeric="^[0-9]+$"

if [ -f $backlight/max_brightness ] && [ -f $backlight/brightness ]; then
	max_brightness=$(cat $backlight/max_brightness)
	brightness=$(cat $backlight/brightness)
else
	echo "cannot query brightness" >&2
	exit 1
fi

if [ $# -ne 1 ]; then
	echo -e "Adjust Screen Brightness\n\nUsage:\n\tadjust-brightness [percent]"
	exit 2
elif ! [[ $percent =~ $numeric ]]; then
	echo "input not numeric" >&2
	exit 3
elif [ $1 -le 0 ] || [ $1 -gt 100 ]; then
	echo "bad range! (1 ~ 100)" >&2
	exit 4
else
	echo $[percent * max_brightness / 100] 2>/dev/null > $backlight/brightness
	if [ $? -ne 0 ]; then
		echo "permission denied, run as administrator." >&2
		exit 5
	fi
fi
