#!/usr/bin/env sh

program="$(basename "$(readlink -f "$0")")"
percent="$1"
backlight="$(readlink -f /sys/class/backlight/*)"

if [ $# -ne 1 ]; then ## no parameter error
	echo "Adjust Screen Brightness"
	echo
	echo "Usage:"
	echo "  $program [0~100]"
	exit 1
elif [ "$(id -u)" -ne 0 ]; then ## not privileged error
	echo "permission denied, run as administrator." >&2
	exit 2
elif ! [ -f $backlight/brightness ]; then ## system file not found error
	echo "cannot query brightness" >&2
	exit 3
elif ! [ -f $backlight/max_brightness ]; then ## system file not found error
	echo "cannot query maximum brightness" >&2
	exit 4
elif [ -z "${percent##*[!0-9]*}" ]; then ## non-numeric input error
	echo "input not numeric" >&2
	exit 4
elif [ "$percent" -le 0 ] || [ "$percent" -gt 100 ]; then ## bad range error
	echo "bad range! (1 ~ 100)" >&2
	exit 5
fi

max_brightness=$(cat $backlight/max_brightness)
echo $((percent * max_brightness / 100)) > $backlight/brightness
