#!/usr/bin/env bash

if [ "$#" -ne 1 ]
then
	echo "Usage:"
	echo
	echo "./generate-manual <file>"
	exit 1
fi

filename="${1%.*}.html"

if [ -f "$filename" ]
then
	content="$(sed -n '/\** WRITE YOUR DATA HERE \**/,/\** END OF DATA \**/p' "$filename")"
fi

exec 3> "$filename"

# HTML Begin
cat << 'EOF' > &3
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<title>Use Case</title>
EOF

# CSS Links
cat << 'EOF' > &3
		<!-- ajax -->
		<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/themes/prism-tomorrow.min.css'>
		<!-- bootstrap -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
		<!-- prims plugin styles -->
		<link href="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/plugins/autolinker/prism-autolinker.min.css" rel="stylesheet">
		<link href="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/plugins/command-line/prism-command-line.min.css" rel="stylesheet">
		<link href="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/plugins/line-highlight/prism-line-highlight.min.css" rel="stylesheet">
		<link href="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/plugins/line-numbers/prism-line-numbers.min.css" rel="stylesheet">
		<link href="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/plugins/toolbar/prism-toolbar.min.css" rel="stylesheet">
EOF

# CSS Style
cat << 'EOF' > &3
		<style>
			.dark-mode {
				background-color: black;
				color: #aaaaaa;
			}

			.dark-mode a {
				color: royalblue;
			}

			.dark-mode .btn {
				background-color: #212529;
			}

			.dark-mode .btn:hover {
				color: #777777;
			}

			img {
				padding-top: 20px;
				padding-bottom: 20px;
				max-width: -moz-available;
			}

			a,
			a:hover,
			a:focus {
				text-decoration: none;
			}

			pre {
				margin-bottom: 1.3rem !important;
			}

			@media only screen and (min-width:720px) {
				.img-responsive {
					max-width: 60%;
					margin-left: auto;
					margin-right: auto;
				}
			}

			/* prism overrides */
			div.code-toolbar>.toolbar a,
			div.code-toolbar>.toolbar button,
			div.code-toolbar>.toolbar span {
				margin-left: 0.7rem;
			}
			.sticky {
				position: sticky !important;
				z-index: 1;
				top: 3%;
			}

			.btn {
				background-color: #f5f5f5;
				height: 40px;
				width: 40px;
				border-radius: 5px;
				text-align: center !important;
				font-size: 18px !important;
			}

			.dropbtn {
			  font-size: 14px;
			  border: none;
			}

			.dropdown {
			  position: relative;
			  display: inline-block;
			}

			.dropdown-content {
			  display: none;
			  position: absolute;
			  background-color: #f1f1f1;
			  z-index: 1;
			}

			.dropdown-content a {
			  color: black;
			  text-decoration: none;
			  display: block;
			}
		</style>
	</head>
EOF

# HTML Body
cat << 'EOF' > &3
	<body class="container">
		<div class="dropdown pull-right sticky">
		  <button class="btn btn-secondary dropbtn" onclick="toggle_settings()" style="font-size: 18px;">
			  &#x2699;
		  </button>
		  <div class="dropdown-content" id="dropdown-content">
			<button id="darkmode-icon" class="btn dropdown-item" onclick="toggle_darkmode()" title="ALT + SHIFT + N" accesskey="N">&#x2600;</button>
			<button class="btn dropdown-item" onclick="zoominLetter()" title="ALT + SHIFT + I" accesskey="i"><span style="font-size: 10px;">A</span><span style="font-size: 18px;">A</span></button>
			<button class="btn dropdown-item" onclick="zoomoutLetter()" title="ALT + SHIFT + O" accesskey="o"><span style="font-size: 18px;">A</span><span style="font-size: 10px;">A</span></button>
			<button class="btn dropdown-item" onclick="defaultFontSize()" title="ALT + SHIFT + D" accesskey="d">&#x21ba;</button>
		  </div>
		</div>
EOF

if [ -n "$content" ]
then
	echo > &3
	echo "$content" > &3
	echo > &3
else
	cat << EOF > &3

		<!-- ********** WRITE YOUR DATA HERE ********** -->

		<!-- ********** END OF DATA ********** -->

EOF
fi


# JS Scripts
cat << 'EOF' > &3
		<!-- bootstrap -->
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
		<!-- prism js -->
		<script src='https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/prism.min.js'></script>
		<!-- prism plugins -->
		<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/plugins/toolbar/prism-toolbar.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/plugins/autolinker/prism-autolinker.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/plugins/command-line/prism-command-line.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/plugins/line-highlight/prism-line-highlight.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/plugins/line-numbers/prism-line-numbers.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/plugins/normalize-whitespace/prism-normalize-whitespace.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/plugins/remove-initial-line-feed/prism-remove-initial-line-feed.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/plugins/show-language/prism-show-language.min.js"></script>
EOF

case "${1##*.}" in
	asm|s)
		echo -e '\t\t<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-asm6502.min.js"></script>'>&3;;
	net|aspnet)
		echo -e '\t\t<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-aspnet.min.js"></script>'>&3;;
	bash)
		echo -e '\t\t<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-bash.min.js"></script>'>&3;;
	c|h)
		echo -e '\t\t<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-c.min.js"></script>'>&3;;
	cmake|CMakeList.txt)
		echo -e '\t\t<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-cmake.min.js"></script>'>&3;;
	cpp|cxx|c++|hpp|hxx)
		echo -e '\t\t<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-c.min.js"></script>'>&3
		echo -e '\t\t<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-cpp.min.js"></script>'>&3;;
	cs|csharp)
		echo -e '\t\t<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-csharp.min.js"></script>'>&3;;
	py|django)
		echo -e '\t\t<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-django.min.js"></script>'>&3;;
	ns)
		echo -e '\t\t<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-dns-zone.min.js"></script>'>&3;;
	docker)
		echo -e '\t\t<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-docker.min.js"></script>'>&3;;
	go)
		echo -e '\t\t<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-go.min.js"></script>'>&3;;
	hcl)
		echo -e '\t\t<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-hcl.min.js"></script>'>&3;;
	ignore)
		echo -e '\t\t<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-ignore.min.js"></script>'>&3;;
	javadoc|jd)
		echo -e '\t\t<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-javadoc.min.js"></script>'>&3;;
	java|jar)
		echo -e '\t\t<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-java.min.js"></script>'>&3;;
	json)
		echo -e '\t\t<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-json5.min.js"></script>'>&3
		echo -e '\t\t<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-json.min.js"></script>'>&3;;
	kotlin)
		echo -e '\t\t<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-kotlin.min.js"></script>'>&3;;
	latex|tex|xetex)
		echo -e '\t\t<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-latex.min.js"></script>'>&3;;
	md|make)
		echo -e '\t\t<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-makefile.min.js"></script>'>&3;;
	md|markdown)
		echo -e '\t\t<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-markdown.min.js"></script>'>&3;;
	ml|matlab)
		echo -e '\t\t<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-matlab.min.js"></script>'>&3;;
	mongo|mongodb|db)
		echo -e '\t\t<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-mongodb.min.js"></script>'>&3;;
	nasm)
		echo -e '\t\t<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-nasm.min.js"></script>'>&3;;
	nginx)
		echo -e '\t\t<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-nginx.min.js"></script>'>&3;;
	oc|objectivec)
		echo -e '\t\t<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-objectivec.min.js"></script>'>&3;;
	opencl)
		echo -e '\t\t<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-opencl.min.js"></script>'>&3;;
	perl)
		echo -e '\t\t<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-perl.min.js"></script>'>&3;;
	phpdoc)
		echo -e '\t\t<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-phpdoc.min.js"></script>'>&3;;
	php)
		echo -e '\t\t<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-php.min.js"></script>'>&3;;
	plsql)
		echo -e '\t\t<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-plsql.min.js"></script>'>&3;;
	powershell)
		echo -e '\t\t<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-powershell.min.js"></script>'>&3;;
	processing)
		echo -e '\t\t<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-processing.min.js"></script>'>&3;;
	prolog)
		echo -e '\t\t<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-prolog.min.js"></script>'>&3;;
	py|python)
		echo -e '\t\t<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-python.min.js"></script>'>&3;;
	qml)
		echo -e '\t\t<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-qml.min.js"></script>'>&3;;
	regex)
		echo -e '\t\t<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-regex.min.js"></script>'>&3;;
	r)
		echo -e '\t\t<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-r.min.js"></script>'>&3;;
	ruby)
		echo -e '\t\t<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-ruby.min.js"></script>'>&3;;
	rust)
		echo -e '\t\t<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-rust.min.js"></script>'>&3;;
	scala)
		echo -e '\t\t<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-scala.min.js"></script>'>&3;;
	sql)
		echo -e '\t\t<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-sql.min.js"></script>'>&3;;
	swift)
		echo -e '\t\t<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-swift.min.js"></script>'>&3;;
	typescript)
		echo -e '\t\t<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-typescript.min.js"></script>'>&3;;
	verilog)
		echo -e '\t\t<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-verilog.min.js"></script>'>&3;;
	vhdl)
		echo -e '\t\t<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-vhdl.min.js"></script>'>&3;;
	vim)
		echo -e '\t\t<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-vim.min.js"></script>'>&3;;
	wasm)
		echo -e '\t\t<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/components/prism-wasm.min.js"></script>'>&3;;
esac

# Custom JS Scripts
cat << 'EOF' > &3
		<script>
			function darkmode() {
				var bodystyle = document.body;
				var icon = document.getElementById('darkmode-icon');
				const dark = sessionStorage.getItem('darkmode');

				if (dark === 'true' || dark == 'undefined') {
					bodystyle.classList.add("dark-mode");
					sessionStorage.setItem('darkmode', true);
					icon.innerHTML = '&#x2600;';
				} else {
					sessionStorage.setItem('darkmode', false);
					bodystyle.classList.remove("dark-mode");
					icon.innerHTML = '&#x263d;';
				}
			}
			darkmode();

			function toggle_darkmode() {
				var bodystyle = document.body;
				var icon = document.getElementById('darkmode-icon');
				const dark = sessionStorage.getItem('darkmode');

				if (dark === 'true' || dark == 'undefined') {
					bodystyle.classList.remove("dark-mode");
					sessionStorage.setItem('darkmode', false);
					icon.innerHTML = '&#x263d;';
					toggle_settings();
				} else {
					sessionStorage.setItem('darkmode', true);
					bodystyle.classList.add("dark-mode");
					icon.innerHTML = '&#x2600;';
					toggle_settings();
				}
			}
			function toggle_settings() {
				var button_list = document.getElementById('dropdown-content');

				if (button_list.style.display != "none") {
					button_list.style.display = "none";
				} else {
					button_list.style.display = "block";
				}
			}
			toggle_settings();

			var current_position = 0;
			function scrollDownListener() {
			  window.addEventListener(
				"keydown",
				function(event) {
				  if (event.key == "j") {
					var screen_height = window.screen.height / 4;
					current_position += screen_height;
					window.scrollTo({top: current_position, behavior: 'smooth'})
				  }
				}
			  )
			}

			function scrollUpListener() {
			  window.addEventListener(
				"keydown",
				function(event) {
				  if (event.key == "k") {
					var screen_height = window.screen.height / 4;
					current_position -= screen_height;
					if (current_position < 0) {
						current_position = 0;
					}
					window.scrollTo({top: current_position, behavior: 'smooth'})
				  }
				}
			  )
			}

			scrollDownListener()
			scrollUpListener()

			var min_level  = 1;
			var max_level  = 12;
			var fontlevel  = parseInt(localStorage.getItem('fontlevel'));
			var fontsize   = parseInt(localStorage.getItem('fontsize'));
			var h1fontsize = parseInt(localStorage.getItem('h1fontsize'));
			var h2fontsize = parseInt(localStorage.getItem('h2fontsize'));
			var h3fontsize = parseInt(localStorage.getItem('h3fontsize'));
			var h4fontsize = parseInt(localStorage.getItem('h4fontsize'));

			if (!fontlevel)  { fontlevel  =  3; localStorage.setItem('fontlevel', 3 ); }
			if (!fontsize)   { fontsize   = 14; localStorage.setItem('fontsize',  14); }
			if (!h1fontsize) { h1fontsize = 32; localStorage.setItem('h1fontsize',32); }
			if (!h2fontsize) { h2fontsize = 24; localStorage.setItem('h2fontsize',24); }
			if (!h3fontsize) { h3fontsize = 18; localStorage.setItem('h3fontsize',18); }
			if (!h4fontsize) { h4fontsize = 16; localStorage.setItem('h4fontsize',16); }

			function defaultFontSize() {
				fontlevel  =  3;
				fontsize   = 14;
				h1fontsize = 32;
				h2fontsize = 24;
				h3fontsize = 18;
				h4fontsize = 16;
				localStorage.setItem('fontlevel',  fontlevel );
				localStorage.setItem('fontsize',   fontsize  );
				localStorage.setItem('h1fontsize', h1fontsize);
				localStorage.setItem('h2fontsize', h2fontsize);
				localStorage.setItem('h3fontsize', h3fontsize);
				localStorage.setItem('h4fontsize', h3fontsize);

				restoreFontSize();
				document.getElementById('dropdown-content').style.display = 'none';
			}

			function zoominLetter() {
				if (fontlevel < max_level) {
					fontlevel += 1;
					fontsize += 2;
					h1fontsize += 2;
					h2fontsize += 2;
					h3fontsize += 2;
					h4fontsize += 2;

					localStorage.setItem('fontlevel', fontlevel);
					localStorage.setItem('fontsize', fontsize);
					localStorage.setItem('h1fontsize', h1fontsize);
					localStorage.setItem('h2fontsize', h2fontsize);
					localStorage.setItem('h3fontsize', h3fontsize);
					localStorage.setItem('h4fontsize', h4fontsize);

					restoreFontSize();
				}
			}

			function zoomoutLetter() {
				if (fontlevel > min_level) {
					fontlevel -= 1;
					fontsize -= 2;
					h1fontsize -= 2;
					h2fontsize -= 2;
					h3fontsize -= 2;
					h4fontsize -= 2;

					localStorage.setItem('fontlevel', fontlevel);
					localStorage.setItem('fontsize', fontsize);
					localStorage.setItem('h1fontsize', h1fontsize);
					localStorage.setItem('h2fontsize', h2fontsize);
					localStorage.setItem('h3fontsize', h3fontsize);
					localStorage.setItem('h4fontsize', h4fontsize);

					restoreFontSize();
				}
			}

			function restoreFontSize() {
				fontsize   = parseInt(localStorage.getItem('fontsize'));
				h1fontsize = parseInt(localStorage.getItem('h1fontsize'));
				h2fontsize = parseInt(localStorage.getItem('h2fontsize'));
				h3fontsize = parseInt(localStorage.getItem('h3fontsize'));
				h4fontsize = parseInt(localStorage.getItem('h4fontsize'));

				var p     = document.getElementsByTagName('p');
				var pre   = document.getElementsByTagName('pre');
				var ul    = document.getElementsByTagName('ul');
				var ol    = document.getElementsByTagName('ol');
				var table = document.getElementsByTagName('table');
				var cite  = document.getElementsByTagName('cite');
				var toc   = document.getElementsByClassName('list-group');
				var bar   = document.getElementsByClassName('difficulty');
				var h1    = document.getElementsByTagName('h1');
				var h2    = document.getElementsByTagName('h2');
				var h3    = document.getElementsByTagName('h3');
				var h4    = document.getElementsByTagName('h4');

				for(i=0 ; i<p.length ; i++) {
					p[i].style.fontSize     = fontsize+"px"
				}
				for(i=0;i<pre.length;i++) {
					pre[i].style.fontSize = fontsize+"px"
				}
				for(i=0;i<ul.length;i++) {
					ul[i].style.fontSize = fontsize+"px"
				}
				for(i=0;i<ol.length;i++) {
					ol[i].style.fontSize = fontsize+"px"
				}
				for(i=0;i<table.length;i++) {
					table[i].style.fontSize = fontsize+"px"
				}
				for(i=0;i<cite.length;i++) {
					cite[i].style.fontSize = fontsize+"px"
				}
				for(i=0;i<toc.length;i++) {
					toc[i].style.fontSize = fontsize+"px"
				}
				for(i=0;i<bar.length;i++) {
					bar[i].style.fontSize = fontsize+"px"
				}
				for(i=0;i<h1.length;i++) {
					h1[i].style.fontSize = h1fontsize+"px"
				}
				for(i=0;i<h2.length;i++) {
					h2[i].style.fontSize = h2fontsize+"px"
				}
				for(i=0;i<h3.length;i++) {
					h3[i].style.fontSize = h3fontsize+"px"
				}
				for(i=0;i<h4.length;i++) {
					h4[i].style.fontSize = h4fontsize+"px"
				}
			}
			restoreFontSize();
		</script>
EOF

# End of HTML
cat << 'EOF' > &3
	</body>
</html>
EOF
